# Generated by Django 4.0.6 on 2022-08-19 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_account_name_remove_account_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='type',
            new_name='drug_type',
        ),
    ]
