# Generated by Django 4.0.6 on 2022-09-05 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0004_alter_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbatch',
            old_name='unit_price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='request_status',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='dispensationPayment',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='dispensationpayment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockbatch',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockBatch_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockItem_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
