# Generated by Django 4.0.6 on 2022-09-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rename_unit_price_stockbatch_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='cat1_price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
