# Generated by Django 4.0.6 on 2022-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockitem_cat1_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='destination',
            field=models.CharField(default='Drug Store', max_length=200),
            preserve_default=False,
        ),
    ]
