# Generated by Django 4.0.6 on 2022-09-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_stockbatch_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='dispensary_quantity',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockitem',
            name='store_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
