# Generated by Django 4.0.6 on 2022-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stockitem_dispensary_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='dispensary_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='store_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
