# Generated by Django 4.0.6 on 2022-09-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stockitem_dispensary_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
