# Generated by Django 4.0.6 on 2022-09-09 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_alter_stockbatch_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='stock_item',
        ),
        migrations.AddField(
            model_name='dosage',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage_stock_batches', to='stock.stockbatch'),
            preserve_default=False,
        ),
    ]
