# Generated by Django 4.0.6 on 2022-09-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_dispensationpayment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dosage',
            old_name='dosage',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='dispensationpayment',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='dosage',
            name='prescription',
        ),
        migrations.AddField(
            model_name='dosage',
            name='frequency',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosage',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dosage',
            name='units',
            field=models.CharField(default='tabs', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='dispensation_payment',
            field=models.ManyToManyField(blank=True, related_name='stock_items', to='stock.dispensationpayment'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescription_stock_batch', to='stock.prescription'),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='stock_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosages', to='stock.stockbatch'),
        ),
    ]
