# Generated by Django 4.0.6 on 2022-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_rename_dosage_dosage_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='category',
            field=models.FloatField(default=3),
            preserve_default=False,
        ),
    ]
