# Generated by Django 4.0.6 on 2022-09-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_prescription_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='category',
            field=models.IntegerField(),
        ),
    ]
