# Generated by Django 4.0.6 on 2022-09-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_alter_prescription_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispensation_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='stock.dispensationpayment'),
        ),
    ]
