# Generated by Django 4.0.6 on 2022-09-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_prescription_dispensation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='paid_amount',
            field=models.FloatField(default=0),
        ),
    ]
