# Generated by Django 4.0.6 on 2022-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_prescription_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='prescription',
            name='balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
