# Generated by Django 4.0.6 on 2022-09-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_remove_prescription_paid_amount_prescription_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.CharField(default='Namyalo Jamilah', max_length=200),
            preserve_default=False,
        ),
    ]
