# Generated by Django 4.0.6 on 2022-09-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_prescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='stashed_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
