# Generated by Django 4.0.6 on 2022-09-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_prescription_stashed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosage',
            name='prescription',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dosage_prescriptions', to='stock.prescription'),
            preserve_default=False,
        ),
    ]
