# Generated by Django 4.0.6 on 2022-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_alter_dosage_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='frequency',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
