# Generated by Django 4.0.6 on 2022-09-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_dosage_frequency_alter_dosage_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='units',
        ),
    ]
