# Generated by Django 4.0.6 on 2022-09-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_remove_dosage_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dosage',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
