# Generated by Django 4.0.6 on 2022-09-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_alter_dosage_frequency_alter_dosage_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosage',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dosage',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
