# Generated by Django 4.0.6 on 2022-09-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_dispensationpayment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosage',
            name='stock_batch',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='dosage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='stock.dosage'),
        ),
    ]
