# Generated by Django 4.0.6 on 2022-09-17 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_remove_dosage_stock_batch_stockbatch_dosage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockbatch',
            old_name='dosage',
            new_name='dosages',
        ),
    ]
