# Generated by Django 4.0.6 on 2022-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_stockbatch_total_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='dispensary_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='store_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
