# Generated by Django 4.0.6 on 2022-09-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_remove_stockbatch_total_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
